### PR TITLE
Update and rename Sonarr to Lidarr

### PR DESCRIPTION
**Pull request by nbonfire**
#### Database Migration
YES | NO

#### Description
Update OSX startup script.

#### Todos
- [ x ] Tests
- [ ] Documentation

#### Issues Fixed or Closed by this PR

*

### CODE REVIEW

**Comment by mattman86** [comment]
Thank you!

**Comment by thezoggy** [comment]
Please remove XEM from this fork.

**Comment by mattman86** [comment]
Sure thing... But could you please elaborate?

**Comment by majora2007** [comment]
@thezoggy we don't need to use xem in this project, but at this time it is not a priority to remove it.

**Comment by thezoggy** [comment]
@majora2007 i agree you dont need xem in the project, i run xem which is why i asked to remove it.

**Comment by majora2007** [comment]
Yup, as we make progress it will be removed. :)

**Pull request merged**
